name: style

on:
  push:
    branches:
      - develop
      - releases/**
      - jcsda_emc_spack_stack
      - release/**
  pull_request:
    branches:
      - develop
      - releases/**
      - jcsda_emc_spack_stack
      - release/**
  workflow_dispatch:
  workflow_call:

concurrency:
  group: style-${{github.ref}}-${{github.event.pull_request.number || github.run_number}}
  cancel-in-progress: true


jobs:
  # Run style checks on the files that have been changed
  style:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@8f4b7f84864484a7bf31766abe9204da3cbe65b3 # @v2
      with:
        fetch-depth: 0
    - uses: actions/setup-python@d27e3f3d7c64b4bbf8e4abfb9b63b83e846e0435 # @v2
      with:
        python-version: '3.11'
        cache: 'pip'
    - name: Install Python packages
      run: |
        python3 -m pip install --upgrade pip six setuptools types-six black==23.1.0 mypy isort clingo flake8
    - name: Setup git configuration
      run: |
        # Need this for the git tests to succeed.
        git --version
        . .github/workflows/setup_git.sh
    - name: Run style tests
      run: |
          share/spack/qa/run-style-tests
